[package]
name = "stream-pic-reader"
version = "0.1.0"
description = "StreamPicReader - webtoon style local image reader"
authors = ["you"]
edition = "2021"

[lib]
name = "stream_pic_reader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = { version = "2", default-features = false, features = ["deflate"] }
